
# --- !Ups
CREATE TABLE IF NOT EXISTS USERS(
ID SERIAL PRIMARY KEY NOT NULL,
FIRST_NAME char(100) NOT NULL,
LAST_NAME  char(100) NOT NULL,
EMAIL  char(255) NOT NULL UNIQUE,
EMAIL_CONFIRMED   BOOLEAN NOT NULL,
PASSWORD  char(255) NOT NULL,
HEADLINE CHAR(150),
BIO  CHAR(1500),
URL_PHOTO_PROFILE TEXT NOT NULL,
SERVICES char(50) NOT NULL,
REGISTRATION_DATE  timestamp NOT NULL
);

CREATE TABLE IF NOT EXISTS ARTICLES(
ID SERIAL PRIMARY KEY NOT NULL,
AUTHOR_ID INT NOT NULL,
CREATION_DATE timestamp NOT NULL,
LAST_UPDATE timestamp NOT NULL,
TITLE  TEXT NOT NULL,
SUMMARY TEXT,
CONTENT  TEXT NOT NULL,
NB_MODIFICATIONS  INT NOT NULL,
READING_TIME  INT NOT NULL,
TAG1 char(100) NOT NULL,
TAG2 char(100)
);

CREATE TABLE IF NOT EXISTS COMMENTS(
ID SERIAL PRIMARY KEY NOT NULL,
USER_ID INT NOT NULL,
ARTICLE_ID INT NOT NULL,
CREATION_DATE timestamp NOT NULL,
LAST_UPDATE timestamp NOT NULL,
CONTENT TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS VIEWS(
ID SERIAL PRIMARY KEY NOT NULL,
USER_ID INT NOT NULL,
ARTICLE_ID INT NOT NULL,
VIEW_DATE timestamp NOT NULL
);

CREATE TABLE IF NOT EXISTS LIKES(
ID SERIAL PRIMARY KEY NOT NULL,
USER_ID INT NOT NULL,
ARTICLE_ID INT NOT NULL,
LIKE_DATE timestamp NOT NULL
);


CREATE TABLE IF NOT EXISTS tags(
ID SERIAL PRIMARY KEY NOT NULL,
NAME char(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS taggings(
ID SERIAL PRIMARY KEY NOT NULL,
TAG_NAME char(100) NOT NULL,
ARTICLE_ID INT NOT NULL,
TAGGING_DATE  timestamp NOT NULL
);

CREATE TABLE IF NOT EXISTS follows(
ID SERIAL PRIMARY KEY NOT NULL,
FOLLOWER_ID INT NOT NULL,
AUTHOR_ID INT NOT NULL,
FOLLOW_DATE timestamp NOT NULL
);

CREATE TABLE IF NOT EXISTS bookmarks(
ID SERIAL PRIMARY KEY NOT NULL,
USER_ID INT NOT NULL,
ARTICLE_ID INT NOT NULL,
BOOKMARK_DATE timestamp NOT NULL
);


CREATE MATERIALIZED VIEW IF NOT EXISTS articles_views AS(
SELECT articles.id AS article_id,
COUNT(views.id) AS nb_views
FROM articles 
LEFT JOIN views ON articles.id = views.article_id
GROUP BY articles.id
);


CREATE MATERIALIZED VIEW IF NOT EXISTS articles_likes AS(
SELECT articles.id AS article_id,
COUNT(likes.id) AS nb_likes
FROM articles 
LEFT JOIN likes ON articles.id = likes.article_id
GROUP BY articles.id
);

CREATE MATERIALIZED VIEW IF NOT EXISTS articles_comments AS(
SELECT articles.id AS article_id,
COUNT(comments.id) AS nb_comments
FROM articles 
LEFT JOIN comments ON articles.id = comments.article_id
GROUP BY articles.id
);


CREATE MATERIALIZED VIEW IF NOT EXISTS articles_bookmarks AS(
SELECT articles.id AS article_id,
COUNT(bookmarks.id) AS nb_bookmarks
FROM articles 
LEFT JOIN bookmarks ON articles.id = bookmarks.article_id
GROUP BY articles.id
);


CREATE MATERIALIZED VIEW IF NOT EXISTS authors_followers AS(
SELECT users.id AS author_id,
COUNT(follows.id) AS nb_followers
FROM users 
LEFT JOIN follows ON users.id = follows.author_id
GROUP BY users.id
);

CREATE MATERIALIZED VIEW IF NOT EXISTS authors_articles AS(
SELECT users.id AS author_id,
COUNT(articles.id) AS nb_articles
FROM users 
LEFT JOIN articles ON users.id = articles.author_id
GROUP BY users.id
);

CREATE MATERIALIZED VIEW IF NOT EXISTS tags_stats AS(

SELECT tags.name AS tag_name,
COUNT(DISTINCT taggings.article_id) AS nb_articles,
SUM(articles_views.nb_views) as nb_views_total
FROM tags 
LEFT JOIN taggings ON tags.name = taggings.tag_name
LEFT JOIN articles_views ON taggings.article_id = articles_views.article_id
GROUP BY tags.name
);

REFRESH MATERIALIZED VIEW articles_views;
REFRESH MATERIALIZED VIEW articles_likes;
REFRESH MATERIALIZED VIEW articles_comments;
REFRESH MATERIALIZED VIEW articles_bookmarks;
REFRESH MATERIALIZED VIEW authors_followers;
REFRESH MATERIALIZED VIEW authors_articles;
REFRESH MATERIALIZED VIEW tags_stats;

# --- !Downs

DROP TABLE USERS;
DROP TABLE ARTICLES;
DROP TABLE COMMENTS;
DROP TABLE VIEWS;
DROP TABLE LIKES;
DROP TABLE TAGS;
DROP TABLE TAGGINGS;
DROP TABLE FOLLOWS;
DROP TABLE articles_views;
DROP TABLE articles_likes;
DROP TABLE articles_comments;
DROP TABLE articles_bookmarks
DROP TABLE authors_followers;
DROP TABLE authors_articles;
DROP TABLE tags_stats